services:
  app:
    build: .
    container_name: cinetrack
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/cinetrack

  mongo:
    image: mongo:6
    container_name: cinetrack_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
